name: mediasoup-worker

on: [pull_request, workflow_dispatch ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        build:
          - os: ubuntu-20.04
            cc: clang
            cxx: clang++
            osarch: linux-amd64
          - os: macos-12
            cc: clang
            cxx: clang++
            osarch: macos-amd64
          - os: windows-2022
            cc: cl
            cxx: cl
            osarch: macos-amd64
        # A single Node.js version should be fine for C++.
        node:
          - 16

    runs-on: ${{ matrix.build.os }}

    env:
      CC: ${{ matrix.build.cc }}
      CXX: ${{ matrix.build.cxx }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm run install-clang-tools
        if: runner.os != 'Windows'

      - name: Configure cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ matrix.build.os }}-node-${{matrix.build.cc}}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.build.os }}-node-${{matrix.build.cc}}-

      - run: npm run worker:build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: worker-${{ matrix.build.osarch }}
          path: worker/out/Release/
